### ISSUE TITLE
[EDGE CASE] Customer

### ISSUE THREAD

**Issue by JoaquinDelaRosa** [JoaquinDelaRosa/CSSWENG-MP#4]
- If there are 2 different customers with the same name, how will we handle it?
- If there is one customer who came back, but has a different company, how will we handle it?
- If the only record containing a certain customer is deleted, do we delete the customer or find some way to retain their information?

**Comment by Joseph-Ano** [comment]
The second bullet can also apply to Customer type right? For example, a customer who first had a customer type of walk-in can come back but this time, with a customer type  of insurance.

If that's the case, would it be better to place the company and the customer type as properties of Order.cs?

**Comment by ethansaqui** [comment]
> If that's the case, would it be better to place the company and the customer type as properties of Order.cs?

wait that might just work

**Comment by JoaquinDelaRosa** [comment]
Fixed in 0.0.1 branch.
